CREATE TABLE IF NOT EXISTS reports (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    report_type VARCHAR(255) NOT NULL,
    data JSON NOT NULL,
    user_agent VARCHAR(255) NOT NULL,
    hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
